pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "3.9.6"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
               git branch: 'feature/jenkins-ci', url: 'https://github.com/yaw4testing/page-object.git'


            }
        }
        stage('maven clean'){
            steps {
                sh 'mvn -f PageObjectLessons/pom.xml clean'
            }
        }
        stage('maven package'){
            steps {
                sh 'mvn -f PageObjectLessons/pom.xml package'
            }
        }
        stage('maven test'){
            steps {
                sh 'mvn -f PageObjectLessons/pom.xml test'
            }
        }
    }
}
